### ISSUE TITLE
Django 1.10 suffers CSRF token mismatch

### ISSUE THREAD

**Issue by florianm** [saxix/django-adminactions#103]
Django-adminactions with Django 1.10 are running into a "CSRF token missing or incorrect" exception when POSTing e.g. "Export to XLS", "Export to CSV" (second screen, after selecting columns and setting export options).

The immediate cause is a mismatch of the CSRF token. This did not happen in Django <=1.9, so it's likely a breaking change courtesy of Django 1.10 rather than a bug in django-adminactions.
It's not:

* stale cookie (deleted all)
* stale cached data (tested in private mode with fresh login/session)
* browser (tested Chrome and Firefox)
* web server settings (tried with runserver and uwsgi)

The issue sounds similar to https://github.com/django-guardian/django-guardian/issues/442 
#99 might be related, hard to tell without context (pun not intended).

Did anyone else run into the same issue, or has anyone gotten adminactions to work with Django 1.10 yet?

**Comment by florianm** [comment]
Update, the issue seems to be django 1.10's render() vs django <= 1.9's render_to_response().

I've upgraded all render_to_response() to read like so:

```
    if django.VERSION[:2] > (1, 9):
        return render(request, template, ctx)
    else:
        return render_to_response(template, RequestContext(request, ctx))
```
This fixes my CSRF token exception, but replicates code over several places: byrows_update.py, export.py, mass_update.py, and merge.py.

compat.py holds the other django-version patches, so we could add a patch to provide a drop-in replacement for render(request, template, context) to older django versions there:

compat.py L 57 ff:
```
# Django 1.10 render() vs Django < 1.10 render_to_response()
if version < (1, 10):
    def render(request, template_name, context=None, content_type=None,
               status=None, using=None):
        """A render() wrapper around render_to_response() for Django < 1.10."""
        return render_to_response(
            template_name, context=RequestContext(request, context),
            content_type=content_type, status=status, using=using)
```

and then in each admin action, e.g. export.py:
```
from django.shortcuts import render_to_response, render
from adminactions import compat # this should override the definition of render() with our wrapper for lower django versions


# at the end of base_export();
return render(request, template, ctx)
```
That works for me too, but I've only tried this on Django 1.10.

@saxix would you be open to me sending a pull request so you can review and advise?

**Comment by saxix** [comment]
Sure please, I'll happy to receive any help on that

**Comment by florianm** [comment]
Great :-) PR is #104 - tested on Django 1.10.2 but not on versions below.

**Comment by saxix** [comment]
https://pypi.python.org/pypi/django-adminactions/1.2

**Comment by florianm** [comment]
@saxix I'm confused - either tag 1.2 does not work with django 1.10 or I'm doing something wrong here.

Just tested with the latest pypi release (django-adminactions>=1.2), and again got CSRF token mismatch.

Example: [export.py](https://github.com/saxix/django-adminactions/blob/1.2/src/adminactions/export.py#L129) still renders to response without alternative.

Could you point me in the right direction?

**Comment by vitorcunha1995** [comment]
I've been through the same problem. I installed 'adminactions' app in my django project and the functions(Graph, Export to xls, export to csv, etc) were accusing the 403 error, " CSFR token missing or incorrect". 

My solution was: Switch all render_to_response methods to render methods.
** Don't forget to import render from django.shortcuts
