### ISSUE TITLE
Forbridden Error

### ISSUE THREAD

**Issue by KaranGajjar** [saxix/django-adminactions#130]
django - 1.10.6
operating system - ubuntu 16.04

when ever i will select an action it gives Forbidden (403)

**Comment by saxix** [comment]
have you granted permission to the user ?

**Comment by petebrowne** [comment]
I have the same issue with Django 1.10.7 and django-adminactions 1.4

I'm testing with a superuser account - it doesn't seem to be related to permissions. It looks like the CSRF token is not added to the form.

**Comment by KaranGajjar** [comment]
i have grant all permission to the user. but it gives same error.

**Comment by xangcastle** [comment]
i have the same proble with django==1.10 and adminactions=1.4

**Comment by saxix** [comment]
just tried the demo application with django 1.10/1.11 and it works as expected, can someone test the last commit to be sure that is nothing related to 1.4 ?

**Comment by petebrowne** [comment]
I've made a minimal Django project that reproduces this error:

https://github.com/petebrowne/django-adminactions-forbidden-error

**Comment by saxix** [comment]
@petebrowne thanks a lot, just tried with current baseline and the error seems fixed. I'm going to release the new version soon

**Comment by petebrowne** [comment]
Yeah it looks like it works off the `master` branch!

**Comment by saxix** [comment]
v1.5 released and available on pypi https://pypi.python.org/pypi/django-adminactions/1.5
