### ISSUE TITLE
How to mass update single model field.

### ISSUE THREAD

**Issue by jayeshbadgujar** [saxix/django-adminactions#134]
See, 

        class UserProfile(models.Model):
            user = models.OneToOneField(to=User,unique=True)
            sites = models.ManyToManyField(Site,blank=True)
            name = models.CharField(max_length=20)
            email = models.CharField(max_length=20)

but i want to update only sites field with mass update

**Comment by saxix** [comment]
see https://django-adminactions.readthedocs.io/en/latest/howto.html#customize-massupdate-form
