### ISSUE TITLE
Merge only copies fields from "other" not considering what user selected.

### ISSUE THREAD

**Issue by PetrDlouhy** [saxix/django-adminactions#139]
In version 1.5, the merge doesn't work as expected. It only copies values from "other" side no matter what the user selected in previous steps.

The bug was introduced in commit f141b3324a5cacca27903bace1771ff363fdc186

**Comment by PetrDlouhy** [comment]
The real problem seems to be, that the `field_names` isn't pass into the `merge` form.

**Comment by PetrDlouhy** [comment]
I finally figured this out. It is caused by following line:
https://github.com/saxix/django-adminactions/blob/develop/src/adminactions/static/adminactions/js/merge.js#L35
which is active not only during merge phase but also during preview phase causing to erase `field_names` input field value.

**Comment by PetrDlouhy** [comment]
@saxix The commit with this fix is still not in the PyPI version. This could lead to data loses. Please release new version. Or I could try to help, if you want.

**Comment by saxix** [comment]
@PetrDlouhy are u available to become official collaborator of adminactions? Seems I do not have required time now, I'll be happy to grant you push privileges.

**Comment by PetrDlouhy** [comment]
@saxix I probably overlooked your comment. Thanks, I would like to become collaborator. Right now, I would like to make order between `master` and `develop` branches and release new version to PyPI.

**Comment by saxix** [comment]
Hey Petr,  please contact me  in private at s.apostolico@gmail.com or https://saxix.slack.com/, you are right there are some issues on the repo that need to be addressed.
