### ISSUE TITLE
Adminactions slow down running whole test suite

### ISSUE THREAD

**Issue by PetrDlouhy** [saxix/django-adminactions#153]
The `create_extra_permission` `post_migrate` signal handler can be quite slow if many apps are installed. Since `post_migrate` is launched during before running tests for every installed application (and creates `get_or_create` call for every model) this slows down also running tests which can be quite annoying during development.
On my project the it slowed running single test from 5s to 20s.

**Comment by saxix** [comment]
maybe we can add a custom command and a check so to remove the post_migrate handler

**Comment by adamhaney** [comment]
This would be hacky but what if 
https://github.com/saxix/django-adminactions/blob/develop/src/adminactions/models.py#L38
was changed to something like:

```python3
import sys
if not 'test' in sys.argv:
    post_migrate.connect(create_extra_permission)
````

I ended up doing something similar in my settings.py to only install/configure the library when I'm not running tests.
