### ISSUE TITLE
Where to put "import adminactions.actions as actions"

### ISSUE THREAD

**Issue by mick-t** [saxix/django-adminactions#155]
Pardon what may be obvious but where do I put the following to add the actions to my site:

```
from django.contrib.admin import site
import adminactions.actions as actions

# register all adminactions
actions.add_to_site(site)
```
When I add this to my settings file, it fails with the following error:

```
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```

I'll add the full stack trace in a comment if needed.

I use the "Two Scoops of Django" approch for my settings files, a base.py file which is imported by the site's setting file. Could that be causing the problem?

**Comment by saxix** [comment]
the `urls.py` file is a good candidate, if does not work try to register any extra action in your [AppConfig.ready](https://docs.djangoproject.com/en/2.1/ref/applications/#django.apps.AppConfig.ready)

**Comment by mick-t** [comment]
Thanks! That works without any stacktraces.

I already had this registered in my urls.py:
```    url(r'^adminactions/', include('adminactions.urls')),```

And adminactions works without registering, are both required?
