### ISSUE TITLE
Mass update error. Too many values to unpack

### ISSUE THREAD

**Issue by JacoBezuidenhout** [saxix/django-adminactions#160]
Good day,

Thank you for the great plugin.

I am getting the following error when I try to use the mass update function:

ValueError: too many values to unpack (expected 2)
(45 additional frame(s) were not displayed)
...
  File "django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "adminactions/templatetags/massupdate.py", line 41, in link_fields_values
    value, label = el

Do you perhaps have a workaround for us?

**Comment by saxix** [comment]
can you share some infos?

- python and django version
- the type of `el`

**Comment by JacoBezuidenhout** [comment]
Sorry @saxix  for not adding that.

I am using Django==2.2.2
To re-create the issue one can use any Django admin changelist-view, select a few and run the mass update action.

Is Django 2.2.2 supported yet? I cannot find the supported versions in the README.md file.

**Comment by saxix** [comment]
Django 2.2 is supported even if it is not properly documented. This issue should be fixed by @aacdd49 in v1.7.1

**Comment by JacoBezuidenhout** [comment]
Thank you very much @saxix and @aacdd49!
