### ISSUE TITLE
Mass update on filefields 

### ISSUE THREAD

**Issue by xanderbotha** [saxix/django-adminactions#161]
Hi There,

Thank you for such an awesome tool! 🥇 

I would like to inquire if perhaps anyone has had issues in regards to document uploads?
I find when trying to mass update my upload  field it says "Updated '3' records"
![Screenshot 2019-09-17 at 15 48 45](https://user-images.githubusercontent.com/15701461/65047393-ae8cdb80-d962-11e9-99e0-b0a44b5b362f.png) . 

But they are in fact not updating these fields at all.

Using : 
Python 3.5.2
Django 2.2.2
django-adminactions==1.8.0

**Comment by xanderbotha** [comment]
Hi Guys,

Anybody with this issue ?

**Comment by JacoBezuidenhout** [comment]
I am having the same problem @xanderbotha, did you perhaps find a solution? The reason for me installing this plugin was mainly for filefields mass update :(

@saxix is this repo still being maintained?

**Comment by xanderbotha** [comment]
HI @JacoBezuidenhout , not yet.

**Comment by saxix** [comment]
the project is still alive, but I do not have time to actively work on it. I fix what I need for my projects but I'll be happy to merge PR if any.

**Comment by JacoBezuidenhout** [comment]
Thank you for the reply @saxix 

Do you experience the same issue with file uploads? Could it be possible that the mass update form does not post files? When I inspect the form I see no "enctype=multipart/form-data" attribute. 

I will check and see if I get time today to test that.

**Comment by saxix** [comment]
FileField is not currently supported. Probably I should remove such kind of
field from the form.

Il giorno ven 15 nov 2019 alle ore 04:42 JacoBezuidenhout <
notifications@github.com> ha scritto:

**Comment by xanderbotha** [comment]
@saxix Thank you for the update!

**Comment by saxix** [comment]
added in 2.1
