### ISSUE TITLE
Django 3.1 FieldDoesNotExist

### ISSUE THREAD

**Issue by jayvdb** [saxix/django-adminactions#166]
FieldDoesNotExist has been removed from django.db.fields in Django 3.1  It is now only in `django.core.exceptions`.

```py
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'adminactions.templatetags.massupdate': cannot import name 'FieldDoesNotExist' from 'django.db.models.fields' (/usr/lib/python3.8/site-packages/django/db/models/fields/__init__.py)
```

**Comment by denizdogan** [comment]
@vecchp Forgot to close this? Is it fixed now? :)

**Comment by vecchp** [comment]
Should be!

**Comment by jonah-juul** [comment]
@vecchp I believe it is in develop not master quite yet

**Comment by vecchp** [comment]
https://pypi.org/project/django-dynamic-fixture/  def in pypi from what I can see

**Comment by domdinicola** [comment]
v1.9 released https://pypi.org/project/django-adminactions/
