### ISSUE TITLE
Fix Documentation about how to use custom MassUpdateForm?

### ISSUE THREAD

**Issue by gziras** [saxix/django-adminactions#170]
Hello! Thank you for your great project!

I was trying to change the mass update form and I was failing by using the guide posted at the [Documentation](https://django-adminactions.readthedocs.io/en/latest/howto.html#customize-massupdate-form).

```
class MyMassUpdateForm(ModelForm):
    class Meta:
        model = MyModel


class MyModelAdmin(admin.ModelAdmin):
    mass_update_form = MyMassUpdateForm


admin.register(MyModel, MyModelAdmin)
```

I managed to get it working with the following code. This  #31  helped.

```
from adminactions.mass_update import MassUpdateForm

class MyMassUpdateForm(MassUpdateForm):
    class Meta:
         fields = ['field1', 'field2']


class MyModelAdmin(admin.ModelAdmin):
    mass_update_form = MyMassUpdateForm


admin.register(MyModel, MyModelAdmin)

```
Perhaps the documentation could change with the above-mentioned code? Or maybe you can provide a more helpful example with the usage of `mass_update_form` and `ModelForm`.

Thank you in advance.
Greg

**Comment by saxix** [comment]
@gziras seems you found an error in the documentation. 

 You could inherit your form from ```ModelForm``` BUT, you must add some mandatory fields as ```_clean```, ```_validate```, ```_selected_action```....

So definetely it is better to inehrit from ```MassUpdateForm```.
