### ISSUE TITLE
mass_update_fields doesn't work

### ISSUE THREAD

**Issue by tolomea** [saxix/django-adminactions#172]
Looking here https://github.com/saxix/django-adminactions/blob/edbfed7714c9455e92bf8d9407dda37c68aea26a/src/adminactions/mass_update.py#L277

```python
    mass_update_exclude = getattr(modeladmin, 'mass_update_exclude', ['pk']) or []
    if 'pk' not in mass_update_exclude:
        mass_update_exclude.append('pk')
```
So mass_update_exclude can't ever be False.
Then a couple of lines later:
```python
    if mass_update_fields and mass_update_exclude:
        raise Exception("Cannot set both 'mass_update_exclude' and 'mass_update_fields'")
```
So you cannot ever set mass_update_fields...

**Comment by saxix** [comment]
I think this is solved in the current version
