### ISSUE TITLE
`TemplateSyntaxError 'extra_urls' is not a registered tag library. Must be one of: ...`

### ISSUE THREAD

**Issue by Zerotask** [saxix/django-adminactions#222]
I noticed that `python manage.py validate_templates` outputs multiple errors for this package, e. g. adminactions/templates/adminactions/helpers/import_fixture.html

> {% extends "admin_extra_urls/action_page.html" %}{% load i18n static extra_urls admin_list admin_urls %}

**Comment by saxix** [comment]
I was able to fins the error in the comment. I see you mention "multiple errors", can I ask you to share them cannot find others,

**Comment by Zerotask** [comment]
I meant the same error, but multiple times
