### ISSUE TITLE
Django 1.8 Warning / Django 1.9 Deprecation for SortedDict

### ISSUE THREAD

**Issue by cyface** [saxix/django-adminactions#66]
`site-packages/adminactions/mass_update.py:75: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  self._dict[field_class] = SortedDict(self.COMMON + args)`

Looks like SortedDict is going away soon, so it's probably something that should be refactored.

Cheers!

Tim

**Comment by rvoicilas** [comment]
Hey, I actually have a patch laying around my computer ... I just pushed it here https://github.com/rvoicilas/django-adminactions/commit/2ddba2ed664feec617457fa65f3b0d1ba27ee341

Let me know if you want to merge this and I'll send you a pull request.

**Comment by saxix** [comment]
sure. no bugs should go unpunished

2015-04-27 23:27 GMT+02:00 Radu Voicilas <notifications@github.com>:

**Comment by rvoicilas** [comment]
Pull request sent https://github.com/saxix/django-adminactions/pull/67

Any plans on releasing a new version ? I'd really want to get rid of this warning.

**Comment by saxix** [comment]
I'll  try to package this week.

2015-04-28 14:09 GMT+02:00 Radu Voicilas <notifications@github.com>:

**Comment by rvoicilas** [comment]
That would be awesome, thanks a lot!

**Comment by saxix** [comment]
merged and released in [0.8.1](https://pypi.python.org/pypi?:action=display&name=django-adminactions&version=0.8.1)
