### ISSUE TITLE
Repeat stale content type warning

### ISSUE THREAD

**Issue by drasco** [saxix/django-adminactions#71]
Hi

As soon as adminactions is added to INSTALLED_APPS, my manage.py migrate begins exhibiting this issue

The following content types are stale and need to be deleted:

    auth | group_permissions
    auth | user_groups
    auth | user_user_permissions

This also occurs for the one ManyToMany field my App has.

I can see in the database, the content types are created when I run migrate, and are again deleted after I enter 'yes' to confirm delete of 'stale' content types.

pip installed adminactions 0.8.3, django 1.7.8, sqlite3 (but also occurs with sqlserver_ado)

Regards

**Comment by viatoriche** [comment]
Fixed in: https://github.com/saxix/django-adminactions/pull/70
You may wait new version in pip, or use develop branch from github

**Comment by saxix** [comment]
fixed in 0.8.4
