### ISSUE TITLE
Trying to use it with django-taggit: AttributeError 'Tag' object has no attribute 'somemodel_set'

### ISSUE THREAD

**Issue by int-ua** [saxix/django-adminactions#72]
I have some tag objects from [`django-taggit`](https://github.com/alex/django-taggit) and I added merge action to the admin. When I try to merge two tags it's throwing exceptions like this:

    ...
    File "adminactions/merge.py", line 139, in merge
       api.merge(master, other, fields=fields, commit=True, related=related)
    File "adminactions/api.py", line 96, in merge
       accessor = getattr(other, name)
    AttributeError: 'Tag' object has no attribute 'somemodel_set'

where `somemodel` is a model with `TaggableManager` field through this mixin:

    class TagModelMixin(models.Model):
        tags = TaggableManager(verbose_name=_('tags'), blank=True)

        class Meta:
            abstract = True

Trying to figure out what to do to make it work, will appreciate any suggestions.

**Comment by int-ua** [comment]
What do you think about this change?

`api.py:96`

                    accessor = getattr(other, name, None)
                    if accessor:
                        rel_fieldname = list(accessor.core_filters.keys())[0].split('__')[0]
                        for r in accessor.all():
                            all_related[name].append((rel_fieldname, r))

**Comment by saxix** [comment]
sounds good, let me check in deep, can you make a pull request with related test ?

**Comment by int-ua** [comment]
I'm not sure how to reproduce the problem in tests. I didn't dig deep enough to understand why there was no `somemodel_set` attribute. Also, it looks like it should be fine if it passes all the existing tests.

**Comment by saxix** [comment]
a ForeignKey with related_name='+' should avoid the creation of 'xxxxx_set' in the related model
