### ISSUE TITLE
Permissions don't work

### ISSUE THREAD

**Issue by olivierdalang** [saxix/django-adminactions#79]
Hi !

On my installation, permissions are not working.

For every user except the super user, I get a "Sorry you do not have rights to execute this action" message, even if the user or it's group have the permission.
For every user, I see all registered adminactions, even if the user has not the permission.

Django : 1.8.5
Django-adminaction : 0.8.5

Is this supposed to work ? If it's a bug (and not some mistake of my part), I'd be glad to give it a shot !
The tool is great, thanks a lot for the work !

**Comment by saxix** [comment]
the expected behaviour should be to check for permission when you try to use any action but display all the registered actions.  (see code [here](https://github.com/saxix/django-adminactions/blob/develop/adminactions/export.py#L39) ).

If you can confirm it is a bug and you send a PR, I will be happy to merge.

**Comment by saxix** [comment]
@olivierdalang any updates on this issue ?

**Comment by olivierdalang** [comment]
Hi, 

Sorry I gave no news, but I tested right now on a fresh install, and it seems indeed that I get
`Sorry you do not have rights to execute this action (testapp.adminactions_export_people)` for any user except super-user, and no matter if the permission is assigned directly to the user or to one of his groups.

I'll definitely give it a shot as soon as I have a bit more time, so I'd suggest to keep the issue open (unless you can't reproduce the bug)

**Comment by saxix** [comment]
did you grant 'adminactions_[ACTION]_[MODEL]' to your  users?

**Comment by olivierdalang** [comment]
yes (from the groups/users admin module)

2015-11-26 13:03 GMT+00:00 saxix <notifications@github.com>:

**Comment by saxix** [comment]
this is strange, just added a [test](https://github.com/saxix/django-adminactions/blob/develop/tests/test_permissions.py) for that, can you try the develop branch ? I'm close to release 1.0 but don't want to package with this error.

**Comment by int-ua** [comment]
I don't have any `adminactions_[ACTION]_[MODEL]` permissions in the user administration (`/admin/auth/user/2/`). Is that a symptom? I also have the permission problem and I can't even assign the permission in the admin panel. Checking if the permission exists in DB.

**Comment by int-ua** [comment]
All `adminactions` permissions are listed in `user.get_all_permissions()` but not in `Permission.objects.all()`

**Comment by saxix** [comment]
permissions are created by [create_extra_permission](https://github.com/saxix/django-adminactions/blob/develop/src/adminactions/models.py#L22) handler, it should be invoked when syncdb/migrate is executed. e8297f8 add new test to check `Permission` table.

**Comment by saxix** [comment]
any updates on this issue ? I'm not able to reproduce it and the related [test](https://github.com/saxix/django-adminactions/blob/e8297f8bd295cc7dfb727539469b406569376534/tests/test_permissions.py) works as expected.

**Comment by olivierdalang** [comment]
Hi,

Sorry for the lack of feedback. I'm testing again right now with 1.0, it works fine on a clean install, but still doesn't work on my site... I tried dropping all permissions, but I still get `Sorry you do not have rights to execute this action` when trying to export entries while logged as an user in a group that has the export permission.

Any idea where the bug could come from ?

**Comment by saxix** [comment]
@olivierdalang realy do not get the issue where come from. I added a test for it. can you share some other info (ie. where did you add the action (Modeladmin or site), are you able to invoke pdb to investigte the issue ?

**Comment by olivierdalang** [comment]
Ok I found the cause, it's because my modules have capital letters. Here's a PR to fix it :
https://github.com/saxix/django-adminactions/pull/89

(there are some conflicts, I'll rebase this afternoon)
