### ISSUE TITLE
merge doesn't work for models related with on_delete=Protect

### ISSUE THREAD

**Issue by olivierdalang** [saxix/django-adminactions#85]
Hi !

When trying to merge objects that have are related with on_delete=Protect, the merge fails because of a `ProtectedError` exception.

When doing a merge and choosing to move the relations, I think one expects that the relations are moved to the "master" before actually deleting the "other", so I don't think the protection should apply here.
Actually, from what I understood of the code, it's exactly what's happening.

Here's an easy hack: https://github.com/olivierdalang/django-adminactions/commit/9938d1072422db0e524ec8ae70627ad1e3ff307a
Not sure if there's no side-effect, I didn't think it through, and I didn't manage to find out how to write a test for this, since it would need to create custom models (with protected relations), hence no PR.

Thanks for the great work !!

**Comment by saxix** [comment]
you are right, the issue happen in the "preview" step. Not sure about your solution, as this could cause the form (and the record) will be validated. 
I'm going to add the feature to 'skip' the preview and add a note to use it if `ProtectedError` happen.

**Comment by mitchelljkotler** [comment]
Any update on this?

**Comment by mitchelljkotler** [comment]
I need this functionality and would be willing to write a PR if it will be merged in.  I would like some explanation for this code from the preview step:

```
with transaction.nocommit():
    form = MForm(request.POST, instance=master)
    other.delete()
form_is_valid = form.is_valid()
```

I understand you are deleting the `other` instance, then validating the `master` model, and then rolling back the transaction.  But I do not understand why - why do you need to validate the `master` instance with the `other` instance deleted?

**Comment by saxix** [comment]
the intention is to invoke model validation, and display errors in a proper way. Using  a form Django calls `full_clean()` and `validate_unique()` on master. This is needed to check that the new instance can be properly saved.
