### ISSUE TITLE
Do not export dates as strings in Excel

### ISSUE THREAD

**Issue by olivierdalang** [saxix/django-adminactions#93]
Hi !

Here, when exporting datetime values to XLS, I get strings like `oct. 8, 2015, 1:58 après-midi` or even `oct. 21, 2015, midi` instead of date values.
I'm not really sure on how the xls exporter library works, but there must be a way to export the date as an excel date instead of a string ? The formatting of the date should be done as a style, not on the value of the cell.
I'm having a look right now, and will make a PR if there's an easy fix !

Bests,

Olivier

**Comment by saxix** [comment]
fixed in 1.5
