### ISSUE TITLE
pip installs version 1.0, but I can't see it here

### ISSUE THREAD

**Issue by olivierdalang** [saxix/django-adminactions#96]
Hi !

When I run `pip install django-adminactions`, I get `Successfully installed django-adminactions-1.0`.
The thing is I can't find a tag or a branch for 1.0 here, so I'm not sure about what's happening, especially since seems some bugs aren't fixed in 1.0, like #79...

On the other hand, if I run `pip install django-adminactions==0.8.5` to get the last version existing here, I get `Invalid template library specified. ImportError raised when trying to load 'adminactions.templatetags.massupdate': No module named 'django.forms.util'`.

I'm under Django 1.9.

Thanks !

Olivier

**Comment by saxix** [comment]
oops... I forgot to push the tag.... just did it..
