### ISSUE TITLE
new PyPI release compatible with Django 1.10

### ISSUE THREAD

**Issue by PetrDlouhy** [saxix/django-adminactions#99]
Current PyPI version is not compatible with stable Django version 1.10. New PyPI release should be made for full Django compatibility.

**Comment by florianm** [comment]
@PetrDlouhy #103 fixes one problem I had with Django 1.10. Same as yours?

**Comment by PetrDlouhy** [comment]
@florianm Similar adjustments are already pulled to the develop branch and working for me. The only problem is, that new PyPI package is missing.

**Comment by florianm** [comment]
great to hear! I've submitted #104 not knowing about that.

**Comment by saxix** [comment]
sorry guys, I have lost the point (maybe too much time I do not work on this code). I'm working on 1.10 compat, fixing broken tests, sadly I do not have much time this period, hope to release a full 1.10 compatible soon.

**Comment by PetrDlouhy** [comment]
@saxix: The develop branch should be fully compatible with 1.10. All unit tests pass, as you can see at https://travis-ci.org/saxix/django-adminfilters

The only thing, that you have to do is release new PyPI package from that branch. Thank you very much :-)

**Comment by saxix** [comment]
sorry for these mistakes, just packaged [1.2](https://pypi.python.org/pypi/django-adminactions/1.2)
